### ISSUE TITLE
Memory management issues

### ISSUE THREAD

**Issue by Dunemaster** [robovm/robovm#1000]
I was testing RoboVM behavior with lots of objects and discovered at least two issues.
See the link for source code for sample application
1) Clicking "Test 100k objects" button result in massive allocations of memory which is not returned to the OS when the "Clear" button is clicked. Is this a bug or I am doing something wrong?

2) Commenting out line 47 causes memory fragmentation issues. Even 100k objects cannot be created
In this case memory can be reserved in advance, but in many other cases that will not be an option.
100k objects in a big application does not seem too much

https://gist.github.com/Dunemaster/5c3661f2a96c00f521d6#file-robovm_memory_tortuture

**Comment by Dunemaster** [comment]
I tested on iPhone 4 with iOS 8.3

**Comment by ntherning** [comment]
Memory is only returned after a few `System.gc()` calls. Call `System.gc()` 3 or more times in succession and you should see memory being returned to the OS.

The GC used in RoboVM (Boehm) is not copying and will not defragment memory. This is rarely a problem for real world apps. Does your test app simulate a real world use case?

**Comment by Dunemaster** [comment]
Yes,  it does. I'm evaluating RoboVM as a means to create a cross-platform mobile version of a large corporate app, which has an internal metadata model, comprising thousand of metadata objects

**Comment by Dunemaster** [comment]
>Memory is only returned after a few System.gc() calls. Call System.gc() 3 or more times in succession >and you should see memory being returned to the OS.
Yes, clicking "clear" several times helps, thank you

**Comment by Dunemaster** [comment]
Also, Apple Swift version uses up 30% less memory than RoboVM version

https://gist.github.com/Dunemaster/08e3b92e1fdbbaa62a9f#file-swift_memory_torture

**Comment by ntherning** [comment]
That's not surprising given that Swift uses reference counting rather than a GC like Java. Memory is likely deallocated shortly after it's not unneeded instead of piling up and deallocated at the next GC. With a GC you will see a quite different memory usage curve.

How are you measuring memory usage BTW? You will not see the actually GC heap usage if you use something like Apple's Instruments to plot memory usage. You only see the total GC allocated heap and how that grows (or shrinks when the GC decides to unmap memory and give it back to the OS). ATM there's no nice way to measure GC heap usage. You will have to log this from within your app using `Runtime.totalMemory()` at regular intervals.

If you are concerned with memory you could look into pooling and reusing objects?

**Comment by Dunemaster** [comment]
I used Apple's instruments, total allocated heap is the thing that's important.

**Comment by Dunemaster** [comment]
The problem is that "test" and "clear" buttons in turn still result in memory warning, memory fragmentation and crash. I think, robovm should resuse memory

**Comment by ntherning** [comment]
RoboVM's GC is not capable of defragmenting memory. We have no plans to change GC at this point in time. RoboVM does unmap memory which returns it to the OS. But only whole pages can be returned so heavy fragmentation could cause memory not to be returned. If memory fragmentation is a concern you should look into alternative memory management solutions (like pooling). ObjC/Swift won't help either since that memory model is also prone to suffer from defragmentation.
