### ISSUE TITLE
Recurring crash triggered by GC

### ISSUE THREAD

**Issue by yanixon** [robovm/robovm#1079]
Hi! I have a LibGDX game that used to work fine with the RoboVM alpha releases, but it's been suffering from crashes ever since the betas, and up until the most recent version.
I can't pinpoint the cause, but it seems to be related to making HTTP requests, especially downloading images. (Removing said calls eliminates the crashes)
The app dies from a SIGABRT after a while, but the same code used to work well with earlier RVM versions.

I've been trying to come up with a sample that reproduces the problem, making similar calls and generating lots of garbage, but it doesn't seem to work. The original code is proprietary, so I couldn't post it even if someone wanted to dig through it. Could someone look at the crash log and suggest what sorts of things it may be related to, just to help me figure out how to reproduce it?

Crash log:
http://pastebin.com/x3pqYKgZ

**Comment by ntherning** [comment]
Looks related to #662

**Comment by ntherning** [comment]
Looking at the code in `darwin_stop_world.c` my guess is that this might be fixed by setting [`GC_query_task_threads`](https://github.com/robovm/bdwgc/blob/master/darwin_stop_world.c#L104) to `TRUE`. This will select a [different code path](https://github.com/robovm/bdwgc/blob/master/darwin_stop_world.c#L584) which queries the OS for the current threads of the process rather than relying on all threads in the GCs list of registered threads to be alive. This code path also handles the case where `thread_suspend()` fails due to a thread which has exited in between the discovery of the thread and the call to `thread_suspend()` which could be what is happening here. Looking at [mono's version of `darwin_stop_world.c`](https://github.com/mono/mono/blob/master/libgc/darwin_stop_world.c) it's based on an old version of bdwgc which only has the code path that `GC_query_task_threads` enables and they submitted the [patch](http://www.hpl.hp.com/hosted/linux/mail-archives/gc/2004-May/000443.html) which handles `thread_suspend()` failures gracefully back in 2004. So my feeling is that we should use this code path too. I've found the [commit](https://github.com/robovm/bdwgc/commit/0563224f6bb7401823f126f82aeb6ef95765d4b3#diff-e2d379aadaac0754305bbc210d71a56d) where the "bad" code path was introduced in bdwgc but no info on why it was needed.

I will try to enable this code path.

**Comment by ntherning** [comment]
Not related to #662.

Created a separate issue for enabling thread discovery in the GC on Darwin: #1113.

**Comment by ntherning** [comment]
@yanixon please try your code with the latest nightly build. I believe this could be fixed now but we don't have code to test this with. See http://docs.robovm.com/advanced-topics/nightlies.html for info on how to use nightlies.

**Comment by yanixon** [comment]
Hello Niklas,

I tried the code, but it didn't fix the issue. The game is still crushing
occasionally.

Thanks,
Yan.

**Comment by ntherning** [comment]
Please post a crash log. And if you use gradle make sure you clear your
gradle cache as described in our docs or you may actually not be using the
latest nightly. Oh and it's 1.6.1-SNAPSHOT you should be using.

**Comment by ntherning** [comment]
@yanixon Still waiting for a crash log. I will assume this is fixed and close this issue. Open a new issue if you still get crashes after the next release which is due to be released within the next couple of days.
