### ISSUE TITLE
final NSObject var becomes a different objc-object when used in block

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#1101]
Consider following code:
```Java
            final PFFile fileMediumImage = new PFFile(mediumImageData);
            System.out.println(fileMediumImage); // prints <PFFile: 0x16e6c1b0>
            fileMediumImage.saveInBackground(new PFSaveCallback() {
                @Override
                public void done(boolean success, NSError error) {
                     System.out.println(fileMediumImage); // prints <NSMethodSignature: 0x16e6c1b0>
                }
            });
```

fileMediumImage is a PFFile on the Java and iOS side. However when the block gets called, PFFile suddenly has turned into a NSMethodSignature or something else. On the Java side it is still a PFFile but on the native side the object has changed, which results in random crashes when we use that object.
The type of the object is totally random, NSMethodSignature, CFRunLoop, UIAlertView, etc. Also the crash report is different everytime.

This can be reproduced with the Parse AnyPic sample.

**Comment by ntherning** [comment]
I think the constructors in `PFFile` doesn't retain the ObjC objects properly on the Java side. Consider this constructor:

```java
    public PFFile(NSData data) {
        super((SkipInit)null);
        setHandle(create(data));
    }
```

The ObjC instance pointer returned by `create(data)` will be autoreleased and `setHandle()` doesn't retain it on the ObJC side. So when the autorelease pool releases the instance it will be freed and reused for some future allocation which is why you see a different type of object when the callback is called.

Another problem with this constructor is that `super((SkipInit)null)` will eventually call `ObjCObject()` which calls `alloc` on the ObjC side to allocate a new ObjC instance of the class. This instance is never released on the Java side due to `setHandle()` and will leak.

Something like this will probably work better:

```java
    public PFFile(NSData data) {
        super(retain(create(data)));
    }
```

I think the extra `retain()` is needed. Without you should see the same kind of problem as the initial one. Please verify.

**Comment by BlueRiverInteractive** [comment]
Fixed with:

```Java
public PFFile(NSData data) {
    super(create(data));
    retain(getHandle());
}
```
