### ISSUE TITLE
App crashes (SIGBUS) when invoking a method on 'self' in an obj-c block invoked from robovm in a background thread

### ISSUE THREAD

**Issue by alexitelman** [robovm/robovm#1109]
Scenario:

1. Obj-C protocol MyProto has method myMethod that gets a block
2. Obj-C class MyLib has method setAndInvokeMyProto that gets an object that implements MyProto and calls its myMethod method and passes a block that inside it calls [self doCallbackLogic] which is in the same class
3. Java class MyProtoImpl implements MyProto and in myMethod it invokes the passed block in a new thread
4. Java class MyLib (bound to Obj-C MyLib) calls setAndInvokeMyProto and passes a new MyProtoImpl

Expected:

doCallbackLogic is invoked

Actual:

App crashes with SIGBUS signal.

Notes:
If the block is invoked on the main thread instead of a new thread it doesn't crash.
If the code inside the block doesn't call a method on 'self' it doesn't crash.

Here's a sample project that demonstrates it:
https://drive.google.com/file/d/0BwxZsZfwfINWbG5CeUN3S3FFVW8/view?usp=sharing

*MyApp is a fully native ios app that demonstrates the same logic, and it works fine.

**Comment by ntherning** [comment]
Your ObjC app crashes too actually. :-)

Anyways, there's an issue in RoboVM with native blocks. They are not retained properly on the Java side. In your test app what happens is that a stack allocated block is passed over to Java. This will work as long as you don't use that block after the call from native to Java returns. When you hand it off to a separate thread a crash will occur since the block has likely been overwritten on the stack.

What we will have to do in RoboVM is to copy the block and the release it when finalized on the Java side.

**Comment by alexitelman** [comment]
Sounds good. Although it's not urgent, as a workaround we are using interfaces (protocols) instead of blocks, which is also more Java-style.. But maybe for others it is more important
