### ISSUE TITLE
IPAs are not accepted by Apple anymore because of CFBundleResourceSpecification in plist

### ISSUE THREAD

**Issue by tobium** [robovm/robovm#1134]
The final Info.plist contains the "CFBundleResourceSpecification" which is not longer accepted by Apple...

We have to remove it in class "IOSTarget"...

Application Loader error message: "ERROR ITMS-9000: "This bundle is invalid. The Info.plist contains an invalid key 'CFBundleResourceSpecification' in bundle..."

**Comment by badlogic** [comment]
Thanks for reporting, will be fixed in the upcoming 1.7 release next week.

**Comment by badlogic** [comment]
I've tested this with our template single view app, and both App Loader as well as ITunes Connect seem to be happy with the included ResourceRules.plist and corresponding entry in the Info.plist. Regardless, it also works without these, which is why we've remove ResourceRules.plist support entirely. This will be included in the 1.7 release later this week.

Thanks for reporting!

**Comment by tobium** [comment]
Did you try with iOS9 and Xcode 7?
