### ISSUE TITLE
Core source code version 1.8 as per GPL

### ISSUE THREAD

**Issue by mvniekerk** [robovm/robovm#1179]
I'm unable to find the core source for version 1.8 (as per GPL) - the last GPL licensed version.

Can you please assist?

**Comment by eGit** [comment]
I second that. The sources of the "Core Software" of RoboVM are available under the terms of the GNU GPL according to the LICENSE.TXT of the RoboVM 1.8 distribution. Where can we download the sources?

**Comment by bugvm** [comment]
I am looking for the core source for version 1.8 as well. Since I need to build a distribution, I am also looking for what artifacts are needed from the core Git repo.  Wiki: Building a distribution (https://github.com/robovm/robovm/wiki/Hacking-on-RoboVM) says "First build and install the artifacts from the core Git repository into your local Maven repository. Then clone the robovm-dist repository (must be in the same folder as the robovm folder from the core repo) and run mvn clean install. You will then have a distribution tar.gz in package/target/."

**Comment by DylanSale** [comment]
Please provide the source for 1.8.

**Comment by xeoshow** [comment]
strongly request it !

**Comment by ashleyj** [comment]
see commit ef091902377c00dc0fb2db87e8d79c8afb5e9010
