### ISSUE TITLE
Intellij: Run/Debug Configuration Auto-Creation

### ISSUE THREAD

**Issue by noblemaster** [robovm/robovm#1210]
Is there an option to prevent RoboVM to auto-create device/simulator run/debug configurations in IntelliJ? I remove them and they come back every time IntelliJ starts up again.

The problem is, I have several iOS modules in my project, so creating generic Run/Debug configurations doesn't make sense. I don't know which module they are for . I need specific Run/Debug configuration specifically for each of the modules. I don't need those auto-generated. I prefer and have no problem at all to create them by hand as I don't need 10 of those clogging the run/debug configurations. 

In any case, can that feature be turned off, i.e. the auto-generation of iOS device/simulator run/debug configurations each time IntelliJ starts?

Thanks :)

**Comment by badlogic** [comment]
It can't be turned off atm, but i can add a setting.

**Comment by badlogic** [comment]
I added a setting, you can find it in the preferences:

![http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202015-12-11%20at%2010.25.53-lWKN3hYSxK.png](http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202015-12-11%20at%2010.25.53-lWKN3hYSxK.png)

The next nightly build of the IDEA plugin will have this fix. Otherwise you can wait for a new release scheduled for next week.

**Comment by noblemaster** [comment]
That looks great! Thanks :-D
