### ISSUE TITLE
System.out.printXX doesn't work in Xcode console

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#216]
System.out.print() and System.out.println() only work when directly used via the RoboVM Eclipse console. These log messages are not shown in the Xcode console.

Maybe the System.out.printXX methods should use the native objc NSLog() method to work properly in all cases?

**Comment by erwin1** [comment]
It would be nice if robovm would provide those wrapper classes and maybe even some kind of system property to enable the wrapping of .out and .err to Foundation.log.
That way the decision for building a more verbose logging version can be deferred to the build system instead of hardcoding it in the app.

@ntherning Do you think it's desirable to have robovm check such a system property at startup and then apply the wrappers?

The same principal could also be applied to Logger.log messages.

**Comment by ntherning** [comment]
Thanks @sehugg and @erwin1 for the fix for this one!
