### ISSUE TITLE
[Feature Request] Support Xcode6-style dynamic frameworks

### ISSUE THREAD

**Issue by thurn** [robovm/robovm#451]
Xcode 6 introduces the ability to create dynamic cocoa touch frameworks very easily without all the difficulty of building static libraries the old way. It would be very useful if robovm supported using these. I've looked into it a bit -- you can pass the new frameworks to the \<frameworks\> block in robovm.xml no problem. An additional step is needed, however, to make sure the framework is copied into the app's bundle. In Xcode 6, there's an "embedded binaries" option in the build settings where you specify this. I believe it just copies everything into the MyApp.app/Frameworks directory.

Without embedding the binary, you just get this error at launch:

Library not loaded: @rpath/MyFramework.framework/MyFramework
  Referenced from: <...>
  Reason: image not found

**Comment by alexitelman** [comment]
We would also appreciate this

**Comment by badlogic** [comment]
Copying alone is not sufficient for app store submission if the framework contains non-device archs. See https://github.com/NativeScript/ios-runtime/issues/46 

Need to take this into account for IPA builds.

**Comment by gilteplitsky** [comment]
this is a really needed feature.
it would be great if you would add it soon.

**Comment by badlogic** [comment]
Spent today investigating this, simulator only. The following needs to be done for Swift dynamic libraries

1. Copy dylibs to $BUNDLE/Frameworks/$FRAMEWORK.framework (copy Swift dylibs for older iOS versions, i think < 8.3).
2. Add search path parent(VM.getExecutableName()) + "/Frameworks" in org.robovm.rt.bro.Runtime
3. Java Classes deriving from Swift need to specify `@NativeClass("$FRAMEWORK.$CLASSNAME)`

**Comment by ntherning** [comment]
Are the changes in `IOSTarget` really required? `org.robovm.rt.bro.Runtime` does the lookup of the framework, not `dyld` so I don't think this should be necessary.

Should we handle static frameworks with regards to resources (#346) in the same way as we do resources within dynamic frameworks? It's unknown to me how one should handle resources in static frameworks.

**Comment by badlogic** [comment]
From what i understood, we do need the changes as the linker adds
references to the dylibs to the executable. They are loaded automatically
on app start, using the rpath to look them up. The changes to IOSTarget
simply set the rpath like Xcode does when linking to dylibs.

I have no good handle framework resources yet.

Are the changes in IOSTarget really required? org.robovm.rt.bro.Runtime
does the lookup of the framework, not dyld so I don't think this should be
necessary.

Should we handle static frameworks with regards to resources (#346
<https://github.com/robovm/robovm/issues/346>) in the same way as we do
resources within dynamic frameworks? It's unknown to me how one should
handle resources in static frameworks.

—
Reply to this email directly or view it on GitHub
<https://github.com/robovm/robovm/issues/451#issuecomment-114218589>.

**Comment by ntherning** [comment]
I see why it's needed now. It's either setting the `rpath` or not linking against the frameworks. We don't really need to link against them at compile time as bro does the linking at runtime using `dlopen()`. But on the other hand we still need a way to specify them in the `robovm.xml` since otherwise we wouldn't know that we need to copy the framework to the app bundle.

**Comment by badlogic** [comment]
Is there any downside to properly setting the rpath?

**Comment by alexitelman** [comment]
Hi guys, are the mentioned changes already committed in the nightly build? Can I test?

**Comment by badlogic** [comment]
Not yet.

**Comment by badlogic** [comment]
The first iteration of this feature will be available in the next nightly. You can find a sample at https://github.com/robovm/robovm-samples/tree/snapshot/CustomFrameworks. Note that the sample is in the snapshot branch of the robovm-samples repository.

Please give it a try and let us know if you run into any issues. The functionality has not yet been tested with signing and submitting to the app store. The dylibs of the framework get embedded and must be signed for submission. RoboVM should do this automatically, but we haven't submitted an app like this yet to ensure this 100%.

**Comment by badlogic** [comment]
Follow up issue for testing in #1030

**Comment by alexitelman** [comment]
In the sample, in ObjCAdder why is the @NativeClass without the framework name like in the SwiftAdder? 
And the @Method selector is "add::" instead of "add:b:" like in SwiftAdder ?
Is this intentional or just a typo?

And also, is the @Library(Library.INTERNAL) really necessary? 
I don't put it in my classes so far.

**Comment by badlogic** [comment]
Mostly because i'm terrible at bindings :) @blueriverinteractive may have
more insights on the selector.

For Library.INTERNAL: yes, that should not be needed.

For the difference in NativeClass: Swift's ObjC bridge will put the bridge
class in a module named after the framework. Hence the prefix in
NativeClass.

**Comment by alexitelman** [comment]
Ok, I've tested your sample it works great, obviously, next I will test with our code, will take me a little longer.

**Comment by BlueRiverInteractive** [comment]
The difference between the selectors comes because how selectors in Swift are composed:

```objc
public func *add*(a*:* Int32, *b:* Int32) -> Int32
```

If you have a function with 1 parameter the selector will be the function name + 1 colon (`add:`). 
If you have multiple parameters you need to add the parameter name + colon to the selector (+ `b:`). But the first parameter name will always be omitted (otherwise the selector would be `adda:b:` which is difficult to read.

```objc
- (int32_t) *add:*(int32_t)a  *:*(int32_t)b;
```

In Objective-C it is a bit different. There you "label" every parameter to compose a long function name (typically something like `multiply:withB:`). You also have parameter names, but these don't get used for the selector. In the sample, the function is lacking a proper parameter label for the second parameter, it is only a colon. Therefore the selector is just `add::`.

**Comment by badlogic** [comment]
Maybe we should make that more idiomatic in the sample. Mea culpa.

**Comment by alexitelman** [comment]
Right, I see now that in ObjCAdder.h (and .m) there's no label for the 'b' param, that's why it's not in the selector... you could've just said that :-)

**Comment by BlueRiverInteractive** [comment]
lol yeah essentially just the 'b' is missing. I kinda faded away when writing that comment :)

**Comment by alexitelman** [comment]
Can Swift enums be bound with robovm? How?

**Comment by alexitelman** [comment]
Hi guys,

I can't seem to run your sample on a device, it only works on simulator..
I'm getting this error in the RoboVM console:

[ERROR] Couldn't start application
org.robovm.libimobiledevice.LibIMobileDeviceException: ApplicationVerificationFailed
	at org.robovm.libimobiledevice.util.AppLauncher$1.error(AppLauncher.java:1001)
	at org.robovm.libimobiledevice.Callbacks.callInstproxyCallback(Callbacks.java:64)

**Comment by badlogic** [comment]
Jupp, need to sign the dylibs. I'm away for the rest of the week, i'll fix
this next monday. Please open a new issue for this.

**Comment by alexitelman** [comment]
Sure, here you go: Issue #1034 
Thanks alot!

**Comment by ntherning** [comment]
BTW, how does this relate to `.embeddedframework` type of frameworks?

**Comment by alexitelman** [comment]
I finished testing all of our swift framework code wrapped with robovm and all is well. Including enums :)
Great job guys, can't wait for the signing issue to be fixed so I can test on a device.

**Comment by alexitelman** [comment]
Hi Robovm guys,

I ran into a little snag, I tried to add a dependency to my swift framework using CocoaPods, but it can't seem to find it when I run the app with Robovm.
I saw that in my framework it links against a framework called Pods_MyFramework, and not directly against the dependency..
So I tried adding Pods_MyFramework to the robovm xml but it didn't  help.

The error I'm getting is the same as before when it couldn't find my framework, only about the dependency framework:

Library not loaded: @rpath/MyDependency.framework/MyDependency
Referenced from: <...MyFramework>
Reason: image not found
