### ISSUE TITLE
PIE disabled. Absolute addressing not allowed

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#503]
Since I've downloaded XCode 6 I get this warning every time I launch an app:

```

PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in _[j]bla.bla.BlaClass[checkcast] from /.../ios/x86/linker.o. To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie
```

Doesn't make any problems so far.

**Comment by ntherning** [comment]
I've looked into this and AFAICS we generate PIE executables already for all architectures except x86 32-bit. So for x86_64, thumbv7 and arm64 PIE is the default. In order to generate PIE for x86 we need to build against OSX 10.7 and iOS 4.2 at the minimum and we need to enable `RelocMode.RelocPIC` when we create the LLVM `TargetMachine`. Setting `TargetMachine.getOptions().setPositionIndependentExecutable(true)` doesn't have any effect on x86 32-bit and seems to be the default on the other platforms.

The reason why PIC isn't the default in LLVM for x86 32-bit could be because PIC code on x86 32-bit is quite slower than non-PIC. I will not enable PIE/PIC for x86 32-bit for now, just suppress the warning when linking. I will also make sure we use the min OS version number in the triple passed to LLVM when creating the `TargetMachine`. I will also bump the min OSX version to 10.7 since that's when the default changed from non-PIE to PIE.
