### ISSUE TITLE
UIView Java subclasses randomly lose member variable values

### ISSUE THREAD

**Issue by mirkonasato** [robovm/robovm#708]
Given this custom UIView subclass:

```java
public class CellView extends UIView {

    private final CellModel cellModel;

    public CellView(CellModel cellModel) {
        requireNonNull(cellModel);
        this.cellModel = cellModel;
    }

    @Override
    public void draw(CGRect rect) {
        requireNonNull(cellModel);   
        //...
    }
}
```
sometimes `cellModel` ends up being `null` in the `draw` method, even though it clearly wasn't `null` in the constructor, right after the view is added to a superview.

Calling `addStrongRef(cellModel)` in the constructor seems effective as a workaround, so I guess it's GC related.

In another similar case, the class has some `double` member variables set to some non-zero values, but at some later point all values are zero. 

I can provide the full app code privately.

**Comment by BlueRiverInteractive** [comment]
This sounds like a GC related issue. I assume you add instances of `CellView` to other `UIViews` via `addSubview()`  and don't keep any references to the `CellViews`?
I've seen similar behavior. GC cleans up the `CellView` instances because they are not used anymore on the Java side. Obj-C then calls into the native draw method of those custom views but all variables have already been reset resulting in null pointer exceptions when accessing these variables. This doesn't happen for standard non-extended CocoaTouch classes because all variables and methods are available  natively on the Obj-C side.
A workaround is to use `addStrongRef()` on those variables or keep local references of these `CellViews`.

It needs more testing but I think we should automatically add strong references to views that get added via `addSubview()`. The same goes for child viewcontrollers of navigation controllers and similar.

**Comment by mirkonasato** [comment]
`CellView` instances are added as subviews to another custom view that does keep track of them, but it may well be that this second custom view becomes unreachable from Java.

I'll add a `view.addStrongRef(customView)` after each `view.addSubview(customView)` and keep an eye on it.

**Comment by mirkonasato** [comment]
Issue hasn't occurred again since adding `addStrongRef()` in a few places so I assume that was it, although it's difficult to prove.

Maybe not strictly a bug in RoboVM but certainly a very unexpected behaviour for people used to  "regular" Java.

If there's a way to automatically prevent GC for Java peers of ObjC instances still in use that'll be ideal. If not, I'd suggest at least making it very clear in the documentation, otherwise it's likely to catch many people out.

**Comment by BlueRiverInteractive** [comment]
This should now be fixed, i.e. you do not need to use addStrongRef() on your custom objects and they still will outlive the GC.
I'll close this issue then, let me know if there's still a problem and I reopen this.
