### ISSUE TITLE
64bit app crashed with https connection

### ISSUE THREAD

**Issue by garsue** [robovm/robovm#739]
When a 64bit application tries to start https connection with `java.net.URLConnection`, it crashes.
I confirmed on iPhone 5s and x86_64 iOS simulators.

In case of an application built as 32bit, it runs collectly.
When using NSURLConnection (RoboVM's binding) instead of java's network APIs, it runs collectly, too.

I made a small sample.
https://github.com/garsue/robovm-https-64bit-failure-sapmle

and symbolicate log.
https://github.com/garsue/robovm-https-64bit-failure-sapmle/blob/master/IOSDemo%20%202015-02-02%2010-17.crash

I ran into this problem when using libgdx's network module.

**Comment by AmazingDreams** [comment]
Might be related to https://github.com/robovm/robovm/issues/715

**Comment by badlogic** [comment]
What RoboVM version are you using? beta-03 or snapshot?

**Comment by garsue** [comment]
I used robovm-1.0.0-SNAPSHOT built on 2015-01-29.

**Comment by cachucan** [comment]
Some of my users were reporting the app crashing on launch (mostly iPhone6 users), when I last distributed using the 32bit-64bit build combo. It is probably due to net connections going out. I gave them the 32-bit version and it installed/worked on their devices just fine. I'm not sure if this is related to #715 because that was resolved for me, at least on 32-bit.

**Comment by ntherning** [comment]
Thanks for the code that reproduces the issue. Here's a stack trace from the crash when running in 64-bit mode on the simulator:

```
Thread 0:: Dispatch queue: com.apple.main-thread
0   Issue739                      	0x0000000106033394 Java_com_android_org_conscrypt_NativeCrypto_SSL_1SESSION_1session_1id + 21
1   Issue739                      	0x00000001062fead7 [J]com.android.org.conscrypt.NativeCrypto.SSL_SESSION_session_id(J)[B + 90
2   Issue739                      	0x00000001062feb2d [j]com.android.org.conscrypt.NativeCrypto.SSL_SESSION_session_id(J)[B[clinit] + 52
3   Issue739                      	0x000000010631c706 [J]com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake()V + 2888 (/OpenSSLSocketImpl.java:413)
4   Issue739                      	0x000000010631cd77 [j]com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake()V[synchronized] + 99
5   Issue739                      	0x00000001062228c0 [J]com.android.okhttp.Connection.upgradeToTls(Lcom/android/okhttp/TunnelRequest;)V + 389 (/Connection.java:149)
6   Issue739                      	0x0000000106222680 [J]com.android.okhttp.Connection.connect(IILcom/android/okhttp/TunnelRequest;)V + 320 (/Connection.java:111)
7   Issue739                      	0x000000010623963d [J]com.android.okhttp.internal.http.HttpEngine.connect()V + 708 (/HttpEngine.java:295)
```

The problem is in `OpenSSLSocketImpl.startHandshake()` which uses an `int` to pass around a pointer which obviously doesn't work on 64-bit. Will change this to using a `long` instead which should fix the problem.

**Comment by ntherning** [comment]
#739 has been fixed now.

**Comment by garsue** [comment]
I confirmed it is fixed with newest SNAPSHOT.
Thanks a lot!
