### ISSUE TITLE
Crash: thread_suspend failed / GC

### ISSUE THREAD

**Issue by mhilbrunner** [robovm/robovm#772]
Hi,

I'm currently running into crashes like these:
http://pastie.org/pastes/9944359/text
http://pastie.org/pastes/9944348/text
using RoboVM-SNAPSHOT running on devices.

Last message is always "thread_suspend failed".

**Comment by mhilbrunner** [comment]
Updating Eclipse Plugin to version from 12.02.2015 and RoboVM Snapshot to 1.0.0-20150213.010929-188 seems to have solved it.

**Comment by mhilbrunner** [comment]
Reopened, as I'm still experiencing the thread_suspend crashes, although rarely.

Seems to be related to a UIAlertView containing input UITextFields, maybe I'll have to addStrongRef(), I'll see.

Recent crash log:
http://pastie.org/pastes/9953514/text

**Comment by mhilbrunner** [comment]
May be related to issue #757?

**Comment by ntherning** [comment]
Please post the entire crash log. I'd like to see what the other threads are doing.

**Comment by mhilbrunner** [comment]
Sorry, sure, here is the entire content for the last log:
http://pastie.org/pastes/9956198/text

Anything else that could help you? Still trying to find how to trigger it, not much luck yet though.

**Comment by BlueRiverInteractive** [comment]
Here's some code that reproduces this error: http://pastebin.com/Fkqs9Qjg
http://imgur.com/VCRkhQX

**Comment by badlogic** [comment]
Tried to reproduce via @BlueRiverInteractive 's sample code locally, but the behaviour isn't occuring.

**Comment by badlogic** [comment]
This little piece of code starts a GC thread that forces the GC to collect (and hence stop the world), then spawns an infinite amount of short lived threads. There should be a chance for a thread being dead and the GC trying to suspend it. Doesn't happen on my machine in neither 32- not 64-bit mode.

```java

public class GcThreadSuspend {
	public static void main(String[] args) throws InterruptedException {
		new Thread(new Runnable() {
			@Override
			public void run() {
				while(true) {
					System.gc();					
				}
			}
		}).start();
		
		int i = 0;
		while(true) {
			final int id = i++;
			Thread t = new Thread(new Runnable() {
				@Override
				public void run() {		
					System.out.println("This is a test" + id);
				}
			});
			t.start();			
		}
	}
}
```

**Comment by badlogic** [comment]
Can reproduce the issue with @BlueRiverInteractive 's example code using PR #738. It's reproduceable on any platform with this PR. 

Boehm keeps a list of threads in a sort of hashmap called `GC_threads`. Each entry is a linked list, with the first node in the list being the last thread that has been spawned and registered with the GC. In case of the crash in Dominik's example app, the last created thread is causing `GC_stop_world` in `darwin_stop_world.c` to fail and abort. It can't suspend the thread, which seems to be still registered with the GC, but already destroyed otherwise. The thread in question is the one created in `testIfCustomObjectsVariablesAreRetained`.

**Comment by badlogic** [comment]
The thread created in Java code goes through the usual detach function, but doesn't unregister from the GC (`unregisterGC` flag is set to false). Next we end up in `GC_inner_start_routine` in `pthread_start.c` in the GC code. That calls `pthread_cleanup_pop(1)` which is supposed to call our thread's cleanup code which should do the unregistering. The comment in `GC_inner_start_routine` says that it will take a lock, so that the GC doesn't traverse a thread that's already been killed. Seems that's not working.

**Comment by badlogic** [comment]
`GC_inner_start_routine` calls into `GC_unregister_my_thread_inner` which calls `GC_delete_thread` which ultimately removes the current thread from the `GC_threads` map. It also removes the mach port of the thread.

Even after that, the main thread will be aborted eventually in `GC_stop_world`. For some reason, the thread we just deleted is still in `GC_threads`. The main thread will actually wait on the lock, until the thread that's killing itself is done doing so.

**Comment by badlogic** [comment]
After the thread killed itself, the `GC_threads` entry contains the thread again! Here's what we get after `GC_delete_thread` is done:

```
(lldb) e p
(GC_thread) $3 = 0x000000010d86a430
(lldb) e p->next
(GC_Thread_Rep *) $4 = 0x000000010d86a830
(lldb) e GC_threads[0]
(GC_thread) $5 = 0x000000010d86a830
```
`p` is our thread. It was in `GC_thread[0]` before the delete took place. After the delete it's set to `0x000000010d86a830`, the next thread in the list.

I continue program execution, and end up in the main thread which tries to stop the world. Here's the content of `GC_threads`:

```
(lldb) e GC_threads[0]
(GC_thread) $7 = 0x000000010d86a430
```
That's the thread we just deleted. Something must have re-registered it after the call to `GC_delete_thread`.

**Comment by badlogic** [comment]
The autorelease pool calls back into our thread after the GC is done with it, which re-registers the thread with the GC outside the thread's control.

![http://sht.tl/qJ3wpl](http://sht.tl/qJ3wpl)

**Comment by badlogic** [comment]
Here's what seems to be happening:

what's happening:
1. we start a thread from Java (doesn't go through attach, but start thread)
2. the thread exits, the GC cleans it up properly and relieves control of the thread
3. Somewhere in thread_start (posix) the autorelease cleanup is called, we attach the thread.
4. no further cleanup is called on the thread, so the thread is not dettached anymore

This means we need to deactivate our little "don't detach until the thread is killed" trick for thread's created from Java. A thread previously created in Java, stopped and then reattached due to a callback (e.g. autorelease pool) needs to detach immediately as it won't get a call when the thread is finally exiting to clean up.

**Comment by ntherning** [comment]
Can we assume that the autorelease cleanup is just another TLS destructor? If that is true "all" we have to do is to make sure our TLS destructor, `attachedThreadExiting()`, is the last destructor that gets called. We can never be certain of that but almost if we just reregister for the first `PTHREAD_DESTRUCTOR_ITERATIONS-1` calls and do the GC thread unregister call only on the last iteration.

**Comment by ntherning** [comment]
But it's likely not that simple since the destructor we register when we attach the second time doesn't get called, right? Can we patch Boehm to check if the thread is dead before it aborts when `thread_suspend()` fails? That would leak I guess since our destructor isn't called.

**Comment by ntherning** [comment]
@mhilbrunner We now believe we have fixed this. Please try with the next nightly build and reopen this issue if you still see this failure.

**Comment by taxi-driver** [comment]
First of all, thank you very much for the wonderful work you've done. I could successfully port my android game to iOS very easily. I'm using RoboVM 1.6.0 plugin in Android Studio. 

Now the issue is I'm getting the "thread_susped failed" error. I'm using Admob interstitials and banners. Any suggestions to resolve this?

**Comment by taxi-driver** [comment]
Ok. somewhat solved it. I was using a timer to show the interstitial after some 600ms. When I removed it(the timer), issue seems to be resolved.

**Comment by badlogic** [comment]
Please provide full error logs (see http://docs.robovm.com/errors.html) and
a samppe project that reproduces the error.
