### ISSUE TITLE
Copy .app and .app.dSYM folders to Spotlight indexed location for symbolication

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm#816]

**Comment by ntherning** [comment]
I've found that Spotlight is picky about what is in the folder. If I just copy the `.app` and `.app.dSYM` to an empty folder in `~/Desktop/` it will be picked up and I just have to select `Re-symbolicate` when viewing a device log. If there are other files in the folder (like copying the entire tmp folder) Spotlight doesn't index anything.

**Comment by ntherning** [comment]
Hmmm, doesn't seem to matter actually. If I specify `-tmp $HOME/Desktop/Foobar` the `.app` and `.app.dSYM` get picked up just fine. But we'd still probably not want to have the tmp dir in a folder which is scanned by Spotlight. I suggest we pick some folder which Xcode uses and copy the `.app` and `.app.dSYM` we produce there. Asynchronously so we don't delay the launch.

**Comment by ntherning** [comment]
Did some more testing to find out where exactly we can put files so that Spotlight picks them up automatically. Xcode uses paths like

```
~/Library/Developer/Xcode/DerivedData/Yada-gpijhaokvtxebibkvggcmolketvv/Build/Products/Debug-iphonesimulator/Yada.app.dSYM
```

Just putting our builds in a sub-folder like `~/Library/RoboVM` or `~/Library/Developer/RoboVM` doesn't make Spotlight index them. I've tried

|Path|Indexed?|
|------|------------|
|`~/Library/Developer/Xcode/DerivedData/RoboVM/<appname>/`|No|
|`~/Library/Developer/Xcode/DerivedData/RoboVM/Products/<appname>/`|No|
|`~/Library/Developer/Xcode/DerivedData/RoboVM/Build/<appname>/`|No|
|`~/Library/Developer/Xcode/DerivedData/RoboVM/Build/Products/<appname>/`|Yes|
|`~/Library/Developer/Xcode/DerivedData/RoboVM/Build/Products/Foobar/<appname>/`|Yes|

It seems like anything matching `~/Library/Developer/Xcode/DerivedData/*/Build/Products/**/` gets indexed.

**Comment by ntherning** [comment]
Should test whether we can hardlink. Would be a nice way to not have to duplicate data. Won't work when using a RAM disk though. But the copying can be asynchronous.

Also, we should keep dSYMs for IPA builds indefinitely with a timestamp but launch builds we can overwrite on each launch.

**Comment by ntherning** [comment]
Hardlinking directories works on OS X but is undocumented and there are no command line tools to do it out of the box. And it seems you need to have administrator rights to do it. We should do something simpler. I will just copy the `dSYM` to an indexed path for now.

**Comment by badlogic** [comment]
In IDEA we don't have .metadata dirs. Build artifacts are copied to
$PROJECT/robovm-build/tmp/. That's also where the logs and xcode files go.
Those should be indexable by spotlight. Haven't tested, but we could do the
same for Eclipse maybe? As a user, I really like to know where my stuff is.
Hiding build artifacts in hidden folders is not so nice in my opinion.

**Comment by ntherning** [comment]
IIUC spotlight's dsym indexer only indexes dsyms under ~/Library/Developer/Xcode/DerivedData/RoboVM/Build/Products/. So we need to copy it there. I have tried with placing the files elsewhere but I cannot get it to index. I haven't found any way to tell spotlight to index dsyms in other folders.
