### ISSUE TITLE
Crash when calling SKScene.getPhysicsWorld().setGravity(...)

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#821]
```Java
SKScene scene = new SKScene();
SKPhysicsWorld physicsWorld = scene.getPhysicsWorld();
physicsWorld.setGravity(new CGVector(0.0, 0.0));
```
It fails at setGravity:
```Java
java.lang.UnsatisfiedLinkError: @Bridge method org/robovm/apple/spritekit/SKPhysicsWorld.$m$setGravity$(Lorg/robovm/apple/spritekit/SKPhysicsWorld;Lorg/robovm/objc/Selector;Lorg/robovm/apple/coregraphics/CGVector;)V not bound
```

**Comment by BlueRiverInteractive** [comment]
Have a breakpoint at `physicsWorld.setGravity` in the example above, you will get a NullPointerException.
Also trying to set a breakpoint at ObjCRuntime.bind() in SKPhysicsWorld crashes the debugger.

**Comment by badlogic** [comment]
I fixed the bug in the debugger. You should be able to set a breakpoint in `ObjCRuntime.bind`. Currently debugging this issue.

**Comment by badlogic** [comment]
The `ObjcRuntime.bind` of the SKScene.class works as intended it seems, at least it doesn't crash. However, stepping over the next few instructions gives us very strange results:

![http://sht.tl/XiqOvx](http://sht.tl/XiqOvx)

why is physicsWorld of type NSObject? That looks very wrong. Would also explain why the next call to `setGravity` fails.

**Comment by badlogic** [comment]
Stepping through the marshaller of the return value for the `physicsWorld` selector. This looks OK:

![http://sht.tl/SvE9e0](http://sht.tl/SvE9e0)

Stepping into toObcCObject still looks good:

![http://sht.tl/4Rix33](http://sht.tl/4Rix33)

That method then tries to map the native peer class to the Java-side class:

![http://sht.tl/fhnWZQ](http://sht.tl/fhnWZQ)

Looks like the native peer class is `PKPhysicsWorld`, not `SKPhysicsWorld`. `toObjCClass` then tries to resolve the ObjCClass for `PKPhysicsWorld`. It fails to find it, so it checks the super class, which is `NSObject`. Our ObjCObject thus has that class instead of `SKPhysicsWorld` wrecking havoc with the rest of the program.

**Comment by ntherning** [comment]
This has resurfaced due to the optimizations I did in #915. After this change we will not generate a specific `@Bridge` method for the `SKScene.getPhysicsWorld()` method but rather reuse the generic one in `$M` which returns `NSObject`. This assumes that there's a binding for the `NSObject` subclass actually returned. But there's no binding for `PKPhysicsWorld` and hence the generic method in `$M` will return an `NSObject` and a `ClassCaseException` will be thrown.

The workaround for this problem is to explicitly annotate the `getPhysicsWorld()` method with the `@Marshaler`:

```java
@Property(selector = "physicsWorld")
@org.robovm.rt.bro.annotation.Marshaler(NSObject.Marshaler.class)
public native SKPhysicsWorld getPhysicsWorld();
```

This has to be done for all methods like `getPhysicsWorld()` that return private ObjC classes that look and feel like a public class but isn't an instance of that class. I don't think we know of any other such method so far.

This is also a huge gotcha for others who try to bind ObjC. It should be very rare though and the workaround is easy once you understand why you get a `ClassCastException` (that's the hard part). Given how much this optimization impacts exe file size I think it's worth it.
