### ISSUE TITLE
soot.VoidType cannot be cast to soot.RefType

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#838]
This error and similar errors can happen when the robovm class compiler is already compiling a project and you change some class in that project in the meantime and save that. 
The RoboVM class compiler compiles the changed classes + dependencies while it also compiles the project. At this time the error `soot.VoidType cannot be cast to soot.RefType` and similar can happen.
The first compile job will stop then and you have to start it.

Seen in eclipse.

**Comment by ntherning** [comment]
Yeah, this is a known issue due to Soot not being reentrant. It's not possible to run two or more compile jobs concurrently in the same JVM. We have now removed the RoboVM Class Builder from Eclipse so this should be less likely to occur. We have a couple of issues for this already: #385, robovm/robovm-eclipse#25.
