### ISSUE TITLE
Compute attributes for properties in custom classes

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm#850]
If we use `@Property` or `@IBOutlet` annotations for custom properties, we need set the proper attributes + type encoding. Otherwise objc will fail with:
>  Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSMethodSignature signatureWithObjCTypes:]: type signature is empty.'

This is mandatory for interface builder integration of IBOutlets.

**Comment by ntherning** [comment]
I believe the important thing is to add proper type encoding to the getter/setter methods when we call `class_addMethod()`. Adding the property and its attributes using `class_addProperty()` seems less important. [This Google Group thread](https://groups.google.com/d/msg/robovm/aYVfjS2Y32s/3RS7drHQ0I0J) suggests that `@IBOutlet`s work as expected if we add proper `@TypeEncoding` annotations to the `@Callback` methods added by the `ObjCMemberPlugin`.

This issue is very much related to #350 and #462.

**Comment by ntherning** [comment]
`@IBOutlet`s seem to be working fine now.
