### ISSUE TITLE
AFC_E_OP_HEADER_INVALID / LOCKDOWN_E_INVALID_SERVICE

### ISSUE THREAD

**Issue by mhilbrunner** [robovm/robovm#909]
My build when deploying to device failed with error `AFC_E_OP_HEADER_INVALID` after the following steps:

>[...]
[DEBUG] [  0%] Beginning upload...
[DEBUG] [  0%] Uploading /Volumes/RoboVM RAM Disk/tmp/svn/workspace/.metadata/.plugins/org.robovm.eclipse.ui/build/project-ios/project-ios/ios/thumbv7/IOSLauncher.app...
[DEBUG] [  1%] Uploading /Volumes/RoboVM RAM Disk/tmp/svn/workspace/.metadata/.plugins/org.robovm.eclipse.ui/build/project-ios/project-ios/ios/thumbv7/IOSLauncher.app/_CodeSignature...
[DEBUG] [  3%] Uploading /Volumes/RoboVM RAM Disk/tmp/svn/workspace/.metadata/.plugins/org.robovm.eclipse.ui/build/project-ios/project-ios/ios/thumbv7/IOSLauncher.app/_CodeSignature/CodeResources...
[DEBUG] [  4%] Uploading /Volumes/RoboVM RAM Disk/tmp/svn/workspace/.metadata/.plugins/org.robovm.eclipse.ui/build/project/project-ios/ios/thumbv7/IOSLauncher.app/Default-568h@2x.png...
[DEBUG] [  6%] Uploading /Volumes/RoboVM RAM Disk/tmp/svn/workspace/.metadata/.plugins/org.robovm.eclipse.ui/build/project/project-ios/ios/thumbv7/IOSLauncher.app/Default-Landscape.png...
[ERROR] Launch failed

After updating the Eclipse plugin to latest nightly, it failed starting the app with the following:
>[ERROR] AppLauncher failed with an exception:
[ERROR] org.robovm.libimobiledevice.LibIMobileDeviceException: LOCKDOWN_E_INVALID_SERVICE
[ERROR] 	at org.robovm.libimobiledevice.LockdowndClient.checkResult(LockdowndClient.java:152)

Simply retrying then solved it and the app started successfully.

**Comment by dooxe** [comment]
Hey, did you solve your problem ?
My build process throw the AFC_E_OP_HEADER_INVALID error almost 80% of the time,
and I was wondering if you know where doesit come from.
Thanks

**Comment by kloylar** [comment]
I have had the same problem when testing on a real device, apparently the problem is due how RoboVM accesses signing identity certificates, when there is more than one certificate in the system I get the error message, for it to work I must delete all extra certificates (Developer ID Application, Developer ID Installer) except developer (Apple Development Certificate with the MAC computer's name)
I delete the certificates and keys using the Keychain access utility, once there is only one certificate I must wait a couple of minutes or restart the system
I am currently using RoboVM SDK/plugin 2.3.9

**Comment by kloylar** [comment]
In my case the project runs correctly in the iOS emulator but with a real device the error appears
I've figured out a way to solve the problem, create any project in XCode, build and run on the real device, while still running compile and run the Libgdx RoboVM project.

Versions:
Libgdx 1.9.10
Android Studio 3.6.3
XCode 11.4.1
RoboVM 2.3.9
iOS 13.4.1
