### ISSUE TITLE
Missing method in NSObject

### ISSUE THREAD

**Issue by magicgoose** [robovm/robovm#963]
According to the documentation ([link](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/NSObject_UIKitAdditions/index.html#//apple_ref/occ/instm/NSObject/awakeFromNib)), NSObject must have `awakeFromNib` method. But it doesn't.

(Although it's still possible to "override" it by using `@Method` annotation, like this:

    @Method
    protected void awakeFromNib() {
        …
    }

)

**Comment by BlueRiverInteractive** [comment]
We currently have `awakeFromNib` in UIViewControllers only. 
@ntherning Should we add that method to NSObject or leave it in UIKit (probably UIResponder or something like that) because it's most likely only used in conjunction with UI controls and I think it shouldn't clutter our NSObject api. What do you think?

**Comment by ntherning** [comment]
I too think it clutters the APIs. But the most compatible way would be to add it to NSObject. So that's what we should do in the long run. But we need the treeshaking first so we don't pull in UIKit as a dependency for any class which is a subclass of NSObject. So for now we can leave it in UIKit. Add an issue for moving it to NSObject once we have the treeshaking in place.
